### ISSUE TITLE
"key" declared void while trying to compile 

### ISSUE THREAD

**Issue by kog001** [xouillet/TypeWriter#1]
First I have to mention that I am a complete noob at progamming so this might be my fault.

I get the following error while trying to compile the code for uploading to a board:

_**sketch_jan20a:240:10: error: variable or field 'key' declared void
 void key(Combi combi)
          ^~~~~
sketch_jan20a:240:10: error: 'Combi' was not declared in this scope
exit status 1
variable or field 'key' declared void**_

The error refers to line 240: void key(Combi combi)

Am I doing something wrong? The only thing that I have modified are the key codes so I can use a different printer. I tested the original code and the error is the same.

Thank you.

**Comment by xouillet** [comment]
Hi,

How are you trying to compile the source ?
I just tried to `git clone` and then `make` on the master branch and I have no issue on my side.

**Comment by kog001** [comment]
I downloaded the .ino file and tried to open it in Arduino. It opens without issues except the compilation error.

**Comment by xouillet** [comment]
Ok, looks more like a bug in the arduino IDE than anything because it does not seems to find the struct that is defined earlier.

Anyway, I've separated the struct and the code with a Typewriter.h file and all should be ok now.

**Comment by kog001** [comment]
Hello!
It is compiling correctly now. Thank you.

One last question. Is there any chance to run the python file under windows? Or do I need a linux VM?

**Comment by xouillet** [comment]
I've never tested it under Windows but it should work, using windows serial port name as `--port` argument (for example `--port COM0`)
